git:
  log:
    showWholeGraph: true
gui:
  theme:
    activeBorderColor:
      - "#fab387"
      - bold
    inactiveBorderColor:
      - "#89b4fa"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#fab387"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#f5e0dc"
