# keympas

# to run lz 
bind L run-shell "tmux neww /home/aniket/.local/bin/lz -l"
bind D run-shell "tmux neww /home/aniket/.local/bin/lz -d"
bind C run-shell "tmux neww /home/aniket/.local/bin/lz -c"

# prefix key
unbind C-b
bind-key C-a send-prefix

# nvim like movement
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# resize pane
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

# panel
unbind %
bind h split-window -h 

unbind '"'
bind v split-window -v


# reload tmux
unbind r 
bind r source-file ~/.config/tmux/tmux.conf \; display-message "config realoded!.."

